CREATE USER fincompare WITH ENCRYPTED PASSWORD 'Mix993xxx';
GRANT ALL PRIVILEGES ON DATABASE FINCOMPARE TO fincompare;

CREATE TABLE EMPLOYEES (
	ID    BIGSERIAL PRIMARY KEY,
	NAME  VARCHAR(127) NOT NULL,
	MAIL  VARCHAR(127) NOT NULL UNIQUE
)

GRANT ALL PRIVILEGES ON TABLE EMPLOYEES TO fincompare;
GRANT ALL PRIVILEGES ON TABLE employees_id_seq TO fincompare;
